name: "Auto-assign themes to PR"

on:
  - pull_request

jobs:
  assign:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}